// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalGSA.Models;

namespace finalGSA.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200424172801_myMigrations")]
    partial class myMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("finalGSA.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompletedBy");

                    b.Property<bool>("IsCompleted");

                    b.Property<string>("Items")
                        .IsRequired();

                    b.Property<string>("Notes");

                    b.Property<int>("PickedUpByID");

                    b.Property<DateTime>("Urgency");

                    b.Property<int>("UserID");

                    b.HasKey("RequestId");

                    b.HasIndex("UserID");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("finalGSA.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<bool>("Status");

                    b.Property<string>("VenmoId")
                        .IsRequired();

                    b.Property<int>("ZipCode");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("finalGSA.Models.Request", b =>
                {
                    b.HasOne("finalGSA.Models.User", "Creator")
                        .WithMany("RequestsCreated")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
